import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#202020] flex flex-col justify-center p-1`}
      >
        {children}
        <footer className="text-gray-700 font-mono pt-3 pr-3 pl-3 text-[8pt]">
          Made by Aran Ramakrishnan, aran.ramakrishnan@gmail.com
        </footer>
      </body>
    </html>
  );
}
